events.listen('recipes', function (e) {

    function seedSoulCreate(essence, ingredient, output) {
        e.remove({ id: 'mysticalagriculture:seed/infusion/' + output })
        e.custom({ "type": "create:mixing", "ingredients": [{ "item": "mysticalagriculture:soulium_seed_base" }, { "item": 'mysticalagriculture:' + essence + '_essence' }, { "item": 'mysticalagriculture:' + essence + '_essence' }, { "item": 'mysticalagriculture:' + essence + '_essence' }, { "item": 'mysticalagriculture:' + essence + '_essence' }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }], "results": [{ "item": "mysticalagriculture:" + output + "_seeds" }] })
    }
    function seedCreate(mystical, ingredient, output) {
        e.remove({ id: 'mysticalagriculture:seed/infusion/' + output })
        e.custom({ "type": "create:mixing", "ingredients": [{ "item": "kubejs:" + mystical + "_seed" }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }], "results": [{ "item": "mysticalagriculture:" + output + "_seeds" }] })
    }
    function seedInsaniumCreate(ingredient, output) {
        e.remove({ id: 'mysticalagriculture:seed/infusion/' + output })
        e.custom({ "type": "create:mixing", "ingredients": [{ "item": "kubejs:insanium_seed" }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }], "results": [{ "item": "mysticalagriculture:" + output + "_seeds" }] })
    }
    function seedDemoniumCreate(ingredient, output) {
        e.remove({ id: 'mysticalagriculture:seed/infusion/' + output })
        e.custom({ "type": "create:mixing", "ingredients": [{ "item": "kubejs:demonium_seed" }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }, { "item": ingredient }], "results": [{ "item": "mysticalagriculture:" + output + "_seeds" }] })
    }
    function seedTier(mystical) {
        e.custom({
            "type": "create:filling",
            "ingredients": [{ "item": "mysticalagriculture:prosperity_seed_base" }, { "fluid": "mysticalagradditions:molten_" + mystical, "nbt": {}, "amount": 288 }], "results": [{ "item": "kubejs:" + mystical + "_seed" }]
        })
    }
    var tier = ["inferium", "prudentium", "tertium", "imperium", "supremium"]
    tier.forEach(T => { seedTier(T) })
    e.custom({
        "type": "create:filling",
        "ingredients": [{ "item": "mysticalagriculture:prosperity_seed_base" }, { "fluid": "kubejs:molten_insanium", "nbt": {}, "amount": 288 }], "results": [{ "item": "kubejs:insanium_seed" }]
    })
    e.custom({
        "type": "create:filling",
        "ingredients": [{ "item": "mysticalagriculture:prosperity_seed_base" }, { "fluid": "kubejs:molten_demonium", "nbt": {}, "amount": 288 }], "results": [{ "item": "kubejs:demonium_seed" }]
    })


    seedCreate('inferium', 'mysticalagriculture:air_agglomeratio', 'air')
    seedCreate('inferium', 'mysticalagriculture:earth_agglomeratio', 'earth')
    seedCreate('inferium', 'mysticalagriculture:water_agglomeratio', 'water')
    seedCreate('inferium', 'mysticalagriculture:fire_agglomeratio', 'fire')
    seedCreate('inferium', 'minecraft:stone', 'stone')
    seedCreate('inferium', 'minecraft:dirt', 'dirt')
    seedCreate('inferium', 'minecraft:ice', 'ice')
    seedCreate('inferium', 'minecraft:oak_log', 'wood')
    seedCreate('prudentium', 'mysticalagriculture:nature_agglomeratio', 'nature')
    seedCreate('prudentium', 'mysticalagriculture:honey_agglomeratio', 'honey')
    seedCreate('prudentium', 'mysticalagriculture:coral_agglomeratio', 'coral')
    seedCreate('prudentium', 'minecraft:coal', 'coal')
    seedCreate('prudentium', 'mysticalagriculture:nether_agglomeratio', 'nether')
    seedCreate('prudentium', 'mysticalagriculture:dye_agglomeratio', 'dye')
    seedCreate('prudentium', 'chisel:basalt/raw', 'basalt')
    seedCreate('prudentium', 'chisel:limestone/raw', 'limestone')
    seedCreate('prudentium', 'chisel:marble/raw', 'marble')
    seedCreate('prudentium', 'mysticalagriculture:mystical_flower_agglomeratio', 'mystical_flower')
    seedCreate('prudentium', 'thermal:apatite', 'apatite')
    seedCreate('prudentium', 'thermal:niter_dust', 'saltpeter')
    seedCreate('prudentium', 'thermal:copper_ingot', 'copper')
    seedCreate('prudentium', 'immersiveengineering:ingot_aluminum', 'aluminum')
    seedCreate('prudentium', 'thermal:sulfur_dust', 'sulfur')
    seedCreate('prudentium', 'appliedenergistics2:silicon', 'silicon')
    seedCreate('prudentium', 'thermal:cinnabar', 'cinnabar')
    seedSoulCreate('prudentium', 'minecraft:mutton', 'sheep')
    seedSoulCreate('prudentium', 'minecraft:porkchop', 'pig')
    seedSoulCreate('prudentium', 'minecraft:beef', 'cow')
    seedSoulCreate('prudentium', 'minecraft:chicken', 'chicken')
    seedSoulCreate('prudentium', 'minecraft:scute', 'turtle')
    seedSoulCreate('prudentium', 'minecraft:slime_ball', 'slime')
    seedSoulCreate('prudentium', 'minecraft:cod', 'fish')
    seedSoulCreate('prudentium', 'minecraft:ink_sac', 'squid')
    seedSoulCreate('tertium', 'minecraft:gunpowder', 'creeper')
    seedSoulCreate('tertium', 'minecraft:bone', 'skeleton')
    seedSoulCreate('tertium', 'minecraft:rotten_flesh', 'zombie')
    seedCreate('tertium', 'quark:biotite', 'ender_biotite')
    seedCreate('tertium', 'mysticalagriculture:prismarine_agglomeratio', 'prismarine')
    seedCreate('tertium', 'minecraft:obsidian', 'obsidian')
    seedCreate('tertium', 'minecraft:redstone', 'redstone')
    seedCreate('tertium', 'minecraft:glowstone_dust', 'glowstone')
    seedCreate('tertium', 'minecraft:quartz', 'nether_quartz')
    seedCreate('tertium', 'minecraft:iron_ingot', 'iron')
    seedCreate('tertium', 'appliedenergistics2:certus_quartz_crystal', 'certus_quartz')
    seedCreate('tertium', 'appliedenergistics2:sky_stone_block', 'sky_stone')
    seedCreate('tertium', 'botania:manasteel_ingot', 'manasteel')
    seedCreate('tertium', 'tconstruct:pig_iron_ingot', 'pig_iron')
    seedCreate('tertium', 'tconstruct:slimesteel_ingot', 'slimesteel')
    seedCreate('tertium', 'tconstruct:tinkers_bronze_ingot', 'tinkers_bronze')
    seedSoulCreate('tertium', 'thermal:basalz_rod', 'basalz')
    seedSoulCreate('tertium', 'thermal:blitz_rod', 'blitz')
    seedSoulCreate('tertium', 'thermal:blizz_rod', 'blizz')
    seedCreate('tertium', 'thermal:lead_ingot', 'lead')
    seedCreate('tertium', 'thermal:silver_ingot', 'silver')
    seedCreate('tertium', 'create:brass_ingot', 'brass')
    seedCreate('tertium', 'create:zinc_ingot', 'zinc')
    seedCreate('tertium', 'thermal:bronze_ingot', 'bronze')
    seedCreate('tertium', 'thermal:tin_ingot', 'tin')
    seedCreate('tertium', 'tdelight:gildedfern_ingot', 'gildedfern')
    seedSoulCreate('tertium', 'minecraft:rabbit', 'rabbit')
    seedSoulCreate('tertium', 'minecraft:spider_eye', 'spider')
    seedCreate('imperium', 'thermal:nickel_ingot', 'nickel')
    seedCreate('imperium', 'mekanism:ingot_steel', 'steel')
    seedSoulCreate('imperium', 'minecraft:ender_pearl', 'enderman')
    seedSoulCreate('imperium', 'minecraft:ghast_tear', 'ghast')
    seedSoulCreate('imperium', 'minecraft:blaze_rod', 'blaze')
    seedSoulCreate('imperium', 'minecraft:experience_bottle', 'experience')
    seedCreate('imperium', 'mysticalagriculture:end_agglomeratio', 'end')
    seedCreate('imperium', 'minecraft:lapis_lazuli', 'lapis_lazuli')
    seedCreate('imperium', 'minecraft:gold_ingot', 'gold')
    seedCreate('imperium', 'powah:crystal_blazing', 'blazing_crystal')
    seedCreate('imperium', 'powah:steel_energized', 'energized_steel')
    seedCreate('imperium', 'appliedenergistics2:fluix_crystal', 'fluix')
    seedCreate('imperium', 'mekanism:ingot_refined_obsidian', 'refined_obsidian')
    seedCreate('imperium', 'mekanism:ingot_refined_glowstone', 'refined_glowstone')
    seedCreate('imperium', 'mekanism:fluorite_gem', 'fluorite')
    seedCreate('imperium', 'mekanism:ingot_osmium', 'osmium')
    seedCreate('imperium', 'botania:elementium_ingot', 'elementium')
    seedCreate('imperium', 'tconstruct:rose_gold_ingot', 'rose_gold')
    seedCreate('imperium', 'tconstruct:cobalt_ingot', 'cobalt')
    seedCreate('imperium', 'immersiveengineering:ingot_hop_graphite', 'hop_graphite')
    seedCreate('imperium', 'thermal:lumium_ingot', 'lumium')
    seedCreate('imperium', 'thermal:signalum_ingot', 'signalum')
    seedCreate('imperium', 'thermal:sapphire', 'sapphire')
    seedCreate('imperium', 'thermal:ruby', 'ruby')
    seedCreate('imperium', 'mekanism:ingot_uranium', 'uranium')
    seedCreate('imperium', 'thermal:invar_ingot', 'invar')
    seedCreate('imperium', 'thermal:electrum_ingot', 'electrum')
    seedCreate('imperium', 'thermal:constantan_ingot', 'constantan')
    seedCreate('imperium', 'materialis:fairy_ingot', 'fairy')
    seedCreate('imperium', 'tinkersarchery:cobalt_tantalum_ingot', 'cobalt_tantalum')
    seedCreate('supremium', 'thermal:enderium_ingot', 'enderium')
    seedCreate('supremium', 'tconstruct:manyullyn_ingot', 'manyullyn')
    seedCreate('supremium', 'tconstruct:queens_slime_ingot', 'queens_slime')
    seedCreate('supremium', 'tconstruct:hepatizon_ingot', 'hepatizon')
    seedCreate('supremium', 'botania:terrasteel_ingot', 'terrasteel')
    seedCreate('supremium', 'draconicevolution:draconium_ingot', 'draconium')
    seedCreate('supremium', 'powah:crystal_niotic', 'niotic_crystal')
    seedCreate('supremium', 'powah:crystal_spirited', 'spirited_crystal')
    seedCreate('supremium', 'powah:uraninite', 'uraninite')
    seedCreate('supremium', 'minecraft:diamond', 'diamond')
    seedCreate('supremium', 'minecraft:emerald', 'emerald')
    seedCreate('supremium', 'minecraft:netherite_ingot', 'netherite')
    seedCreate('supremium', 'byg:pendorite_ingot', 'pendorite')
    seedCreate('supremium', 'tdelight:rosenquartz_ingot', 'rosenquartz')
    seedCreate('supremium', 'tdelight:hamletite_ingot', 'hamletite')
    seedCreate('supremium', 'industrialforegoing:pink_slime_ingot', 'pinkslime')
    seedCreate('supremium', 'tinkersarchery:galaxy_alloy_ingot', 'niillite')
    seedSoulCreate('supremium', 'minecraft:wither_skeleton_skull', 'wither_skeleton')
    seedInsaniumCreate('minecraft:nether_star', 'nether_star')
    seedInsaniumCreate('mysticalagradditions:dragon_scale', 'dragon_egg')
    seedInsaniumCreate('draconicevolution:awakened_draconium_ingot', 'awakened_draconium')
    seedInsaniumCreate('powah:crystal_nitro', 'nitro_crystal')
    seedInsaniumCreate('mythicbotany:alfsteel_armor_upgrade', 'alfsteel')
    seedDemoniumCreate('draconicevolution:chaos_shard', 'chaotic')

})