events.listen('recipes', function (e) {

    function igneousExtruder(fluid, bottom, output){e.custom({"type": "thermal:rock_gen","adjacent": fluid,"below": bottom,"result": {"item": output}})}

  //Igneous Extruder
  igneousExtruder('minecraft:water', 'mysticalagriculture:soulstone', 'mysticalagriculture:soulstone')
  igneousExtruder('minecraft:water', 'minecraft:nether_bricks', 'minecraft:netherrack')
  igneousExtruder('minecraft:water', 'minecraft:soul_soil', 'minecraft:soul_sand')
  igneousExtruder('minecraft:water', 'minecraft:polished_andesite', 'minecraft:andesite')
  igneousExtruder('minecraft:water', 'minecraft:polished_diorite', 'minecraft:diorite')
  igneousExtruder('minecraft:water', 'minecraft:polished_granite', 'minecraft:granite')
  igneousExtruder('minecraft:water', 'create:polished_gabbro', 'create:gabbro')
  igneousExtruder('minecraft:water', 'create:polished_dolomite', 'create:dolomite')
  igneousExtruder('minecraft:water', 'create:polished_limestone', 'create:limestone')
  igneousExtruder('minecraft:water', 'minecraft:end_stone_bricks', 'minecraft:end_stone')
  igneousExtruder('minecraft:water', 'create:polished_scoria', 'create:scoria')
  igneousExtruder('minecraft:water', 'create:polished_dark_scoria', 'create:dark_scoria')
  igneousExtruder('minecraft:water', 'byg:dacite_bricks', 'byg:dacite')
  igneousExtruder('minecraft:water', 'byg:red_rock_bricks', 'byg:red_rock')
  igneousExtruder('minecraft:water', 'byg:scoria_stonebricks', 'byg:scoria_stone')
  igneousExtruder('minecraft:water', 'byg:polished_soapstone', 'byg:soapstone')
  igneousExtruder('minecraft:water', 'quark:polished_basalt', 'quark:basalt')
  igneousExtruder('minecraft:water', 'quark:polished_slate', 'quark:slate')
  igneousExtruder('minecraft:water', 'byg:black_sandstone', 'byg:black_sand')
  igneousExtruder('minecraft:water', 'byg:white_sandstone', 'byg:white_sand')
  igneousExtruder('minecraft:water', 'byg:blue_sandstone', 'byg:blue_sand')
  igneousExtruder('minecraft:water', 'byg:purple_sandstone', 'byg:purple_sand')
  igneousExtruder('minecraft:water', 'byg:pink_sandstone', 'byg:pink_sand')
  igneousExtruder('minecraft:water', 'quark:polished_limestone', 'quark:limestone')
  igneousExtruder('minecraft:water', 'byg:blue_nether_bricks', 'byg:blue_netherrack')
  igneousExtruder('minecraft:water', 'minecraft:purpur_block', 'byg:purpur_stone')
  igneousExtruder('minecraft:water', 'byg:ether_stone', 'byg:ether_stone')
  igneousExtruder('minecraft:water', 'byg:packed_black_ice', 'byg:black_ice')
  igneousExtruder('minecraft:water', 'quark:polished_jasper', 'quark:jasper')
  igneousExtruder('minecraft:water', 'quark:polished_myalite', 'quark:myalite')
  igneousExtruder('minecraft:water', 'quark:polished_deepslate', 'quark:deepslate') 
  igneousExtruder('minecraft:water', 'chisel:limestone/raw', 'chisel:limestone/raw') 
  igneousExtruder('minecraft:water', 'chisel:basalt/raw', 'chisel:basalt/raw') 
  igneousExtruder('minecraft:water', 'chisel:marble/raw', 'chisel:marble/raw') 
  igneousExtruder('minecraft:water', 'betterendforge:violecite_polished', 'betterendforge:violecite') 
  igneousExtruder('minecraft:water', 'quark:polished_marble', 'quark:marble') 
  igneousExtruder('minecraft:water', 'quark:brimstone_bricks', 'quark:brimstone') 
  igneousExtruder('minecraft:water', 'byg:polished_travertine', 'byg:travertine') 
  })