events.listen('block.registry', function (e) {
	e.create('crushed_sky_stone').material('sand').hardness(1.0).displayName('Crushed Sky Stone')
	e.create('compressed_sky_stone').material('stone').hardness(40.0).displayName('Compressed Sky Stone')
	e.create('compressed_crushed_sky_stone').material('sand').hardness(5.0).displayName('Compressed Crushed Sky Stone')
	e.create('black_gravel').material('sand').hardness(1.0).displayName('Black Gravel')
	e.create('compressed_black_gravel').material('sand').hardness(2.0).displayName('Compressed Black Gravel')
	e.create('compressed_blackstone').material('stone').hardness(1.5).displayName('Compressed Blackstone')
	e.create('chaotic_crux').material('rock').hardness(0.5).displayName('Chaotic Crux')
	e.create('alfsteel_crux').material('rock').hardness(0.5).displayName('Alfsteel Crux')
	e.create('slate_blank').material('rock').hardness(1.5).displayName('Blank Slate Block')
	e.create('slate_reinforced').material('rock').hardness(1.5).displayName('Reinforced Slate Block')
	e.create('slate_imbued').material('rock').hardness(1.5).displayName('Imbued Slate Block')
	e.create('slate_demonic').material('rock').hardness(1.5).displayName('Demonic Slate Block')
	e.create('slate_ethereal').material('rock').hardness(1.5).displayName('Ethereal Slate Block')
	e.create('dragonscales_block').material('dragon_egg').hardness(1.5).displayName('Dragon Scales Block')
	e.create('red_alloy_ingot_block').material('metal').hardness(1.5).displayName('Red Alloy Ingot Block')
	e.create('electrotine_alloy_ingot_block').material('metal').hardness(1.5).displayName('Electrotine Alloy Ingot Block')
	e.create('polished_rose_quartz_block').material('metal').hardness(1.5).displayName('Polished Rose Quartz Block')
	e.create('shadow_steel_block').material('metal').hardness(1.5).displayName('Shadow Steel Block')
	e.create('refined_radiant_block').material('metal').hardness(1.5).displayName('Refined Radiant Block')
	e.create('pink_slime_ingot_block').material('metal').hardness(1.5).displayName('Pink Slime Ingot Block')
	e.create('machinarium_block').material('iron').hardness(0.5).displayName('Machinarium Block')
	e.create('demonium_block').material('rock').hardness(1.5).displayName('Demonium Block')
	e.create('demonium_gemstone_block').material('rock').hardness(1.5).displayName('Demonium gemstone Block')
	e.create('demonium_ingot_block').material('metal').hardness(1.5).displayName('Demonium Ingot Block')
	e.create('livingrock_air').material('stone').hardness(1.5).displayName('Livingrock of Air')
	e.create('livingrock_alfheim').material('stone').hardness(1.5).displayName('Livingrock of Alfheim')
	e.create('livingrock_asgard').material('stone').hardness(1.5).displayName('Livingrock of Asgard')
	e.create('livingrock_autumn').material('stone').hardness(1.5).displayName('Livingrock of Autumn')
	e.create('livingrock_earth').material('stone').hardness(1.5).displayName('Livingrock of Earth')
	e.create('livingrock_envy').material('stone').hardness(1.5).displayName('Livingrock of Envy')
	e.create('livingrock_fire').material('stone').hardness(1.5).displayName('Livingrock of Fire')
	e.create('livingrock_gluttony').material('stone').hardness(1.5).displayName('Livingrock of Gluttony')
	e.create('livingrock_greed').material('stone').hardness(1.5).displayName('Livingrock of Greed')
	e.create('livingrock_helheim').material('stone').hardness(1.5).displayName('Livingrock of Helheim')
	e.create('livingrock_jotunheim').material('stone').hardness(1.5).displayName('Livingrock of Jötunheim')
	e.create('livingrock_lust').material('stone').hardness(1.5).displayName('Livingrock of Lust')
	e.create('livingrock_mana').material('stone').hardness(1.5).displayName('Livingrock of Mana')
	e.create('livingrock_midgard').material('stone').hardness(1.5).displayName('Livingrock of Midgard')
	e.create('livingrock_muspelheim').material('stone').hardness(1.5).displayName('Livingrock of Muspelheim')
	e.create('livingrock_nidavellir').material('stone').hardness(1.5).displayName('Livingrock of Nidavellir')
	e.create('livingrock_niflheim').material('stone').hardness(1.5).displayName('Livingrock of Niflheim')
	e.create('livingrock_pride').material('stone').hardness(1.5).displayName('Livingrock of Pride')
	e.create('livingrock_sloth').material('stone').hardness(1.5).displayName('Livingrock of Sloth')
	e.create('livingrock_spring').material('stone').hardness(1.5).displayName('Livingrock of Spring')
	e.create('livingrock_summer').material('stone').hardness(1.5).displayName('Livingrock of Summer')
	e.create('livingrock_vanaheim').material('stone').hardness(1.5).displayName('Livingrock of Vanaheim')
	e.create('livingrock_water').material('stone').hardness(1.5).displayName('Livingrock of Water')
	e.create('livingrock_winter').material('stone').hardness(1.5).displayName('Livingrock of Winter')
	e.create('livingrock_wrath').material('stone').hardness(1.5).displayName('Livingrock of Warth')

	//Slab Process Create
	e.create('livingrock_air_slab').material('stone').hardness(1.5).displayName('Livingrock of Air').type('slab')
	e.create('livingrock_alfheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Alfheim').type('slab')
	e.create('livingrock_asgard_slab').material('stone').hardness(1.5).displayName('Livingrock of Asgard').type('slab')
	e.create('livingrock_autumn_slab').material('stone').hardness(1.5).displayName('Livingrock of Autumn').type('slab')
	e.create('livingrock_earth_slab').material('stone').hardness(1.5).displayName('Livingrock of Earth').type('slab')
	e.create('livingrock_envy_slab').material('stone').hardness(1.5).displayName('Livingrock of Envy').type('slab')
	e.create('livingrock_fire_slab').material('stone').hardness(1.5).displayName('Livingrock of Fire').type('slab')
	e.create('livingrock_gluttony_slab').material('stone').hardness(1.5).displayName('Livingrock of Gluttony').type('slab')
	e.create('livingrock_greed_slab').material('stone').hardness(1.5).displayName('Livingrock of Greed').type('slab')
	e.create('livingrock_helheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Helheim').type('slab')
	e.create('livingrock_jotunheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Jötunheim').type('slab')
	e.create('livingrock_lust_slab').material('stone').hardness(1.5).displayName('Livingrock of Lust').type('slab')
	e.create('livingrock_mana_slab').material('stone').hardness(1.5).displayName('Livingrock of Mana').type('slab')
	e.create('livingrock_midgard_slab').material('stone').hardness(1.5).displayName('Livingrock of Midgard').type('slab')
	e.create('livingrock_muspelheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Muspelheim').type('slab')
	e.create('livingrock_nidavellir_slab').material('stone').hardness(1.5).displayName('Livingrock of Nidavellir').type('slab')
	e.create('livingrock_niflheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Niflheim').type('slab')
	e.create('livingrock_pride_slab').material('stone').hardness(1.5).displayName('Livingrock of Pride').type('slab')
	e.create('livingrock_sloth_slab').material('stone').hardness(1.5).displayName('Livingrock of Sloth').type('slab')
	e.create('livingrock_spring_slab').material('stone').hardness(1.5).displayName('Livingrock of Spring').type('slab')
	e.create('livingrock_summer_slab').material('stone').hardness(1.5).displayName('Livingrock of Summer').type('slab')
	e.create('livingrock_vanaheim_slab').material('stone').hardness(1.5).displayName('Livingrock of Vanaheim').type('slab')
	e.create('livingrock_water_slab').material('stone').hardness(1.5).displayName('Livingrock of Water').type('slab')
	e.create('livingrock_winter_slab').material('stone').hardness(1.5).displayName('Livingrock of Winter').type('slab')
	e.create('livingrock_wrath_slab').material('stone').hardness(1.5).displayName('Livingrock of Warth Slab').type('slab')
})