events.listen('fluid.registry', e => {
  e.create('overworld_icing').textureThick(0x91c062).displayName('Overworld Icing').bucketColor(0x91c062)
  e.create('end_icing').textureThick(0xf3f7bb).displayName('End Icing').bucketColor(0xf3f7bb)
  e.create('nether_icing').textureThick(0xb92f32).displayName('Nether Icing').bucketColor(0xb92f32)
  e.create('molten_insanium').textureThick(0x630097).displayName('Molten Insanium').bucketColor(0x630097)
  e.create('molten_demonium').textureThick(0x111111).displayName('Molten Demonium').bucketColor(0x111111)
  e.create('pure_dragon_blood').textureThin(0x9124d7).displayName('Pure Dragon Blood').bucketColor(0x9124d7)
  e.create('cold_dragon_blood').textureThin(0x8b55dc).displayName('Cold Dragon Blood').bucketColor(0x8b55dc)
  e.create('dragon_blood').textureThin(0x5317c0).displayName('Dragon Blood').bucketColor(0x5317c0)
  e.create('mana').textureThin(0x4cbcfc).displayName('Mana').bucketColor(0x4cbcfc)
  e.create('liquid_prosperity').textureThin(0xaecccc).displayName('Liquid Prosperity').bucketColor(0xaecccc)
  e.create('electrified_water').textureThin(0x38bcb4).displayName('Electrified water').bucketColor(0x38bcb4)
  e.create('molten_black_iron').textureThick(0x090909).displayName('Molten Black Iron').bucketColor(0x090909)
  e.create('flux_waste').textureThin(0x0f0f0f).displayName('Flux Waste').bucketColor(0x0f0f0f)
  //Creative fluids
  e.create('1alloy').textureThick(0xd10000).displayName('§4The First Combination Alloy').bucketColor(0xd10000)
  e.create('2alloy').textureThick(0xce5200).displayName('§6The Second Combination Alloy').bucketColor(0xce5200)
  e.create('3alloy').textureThick(0xccaa00).displayName('§eThe Third Combination Alloy').bucketColor(0xccaa00)
  e.create('4alloy').textureThick(0x3dcc00).displayName('§aThe Fourth Combination Alloy').bucketColor(0x3dcc00)
  e.create('5alloy').textureThick(0x0077cc).displayName('§9The Fifth Combination Alloy').bucketColor(0x0077cc)
  e.create('6alloy').textureThick(0x8b00cc).displayName('§5The Sixth Combination Alloy').bucketColor(0x8b00cc)
  e.create('7alloy').textureThick(0xcc00b0).displayName('§dThe Seventh Combination Alloy').bucketColor(0xcc00b0)
  e.create('ultimate_alloy').displayName('The Ultimate Alloy').textureStill("kubejs:fluid/ultimate_alloy").textureFlowing("kubejs:fluid/ultimate_alloy_flow").bucketColor(0x998000)


})