events.listen('item.registry', function (e) {
	e.create('raw_cobalt').displayName('Raw Cobalt')
	e.create('cobalt_piece_ore').displayName('Cobalt Ore Piece')
	e.create('raw_tin').displayName('Raw Tin')
	e.create('tin_piece_ore').displayName('Tin Ore Piece')
	e.create('raw_osmium').displayName('Raw Osmium')
	e.create('osmium_piece_ore').displayName('Osmium Ore Piece')
	e.create('raw_iron').displayName('Raw Iron')
	e.create('iron_piece_ore').displayName('Iron Ore Piece')
	e.create('raw_gold').displayName('Raw Gold')
	e.create('gold_piece_ore').displayName('Gold Ore Piece')
	e.create('raw_copper').displayName('Raw Copper')
	e.create('copper_piece_ore').displayName('Copper Ore Piece')
	e.create('raw_silver').displayName('Raw Silver')
	e.create('silver_piece_ore').displayName('Silver Ore Piece')
	e.create('raw_aluminum').displayName('Raw Aluminum')
	e.create('aluminum_piece_ore').displayName('Aluminum Ore Piece')
	e.create('raw_nickel').displayName('Raw Nickel')
	e.create('nickel_piece_ore').displayName('Nickel Ore Piece')
	e.create('tinkersarchery:raw_tantalum').displayName('Raw Tantalum')
	e.create('create:raw_zinc').displayName('Raw Zinc')
	e.create('mythicbotany:raw_elementium').displayName('Raw Elementium')
	e.create('zinc_piece_ore').displayName('Zinc Ore Piece')
	e.create('raw_lead').displayName('Raw Lead')
	e.create('lead_piece_ore').displayName('Lead Ore Piece')
	e.create('raw_uranium').displayName('Raw Uranium')
	e.create('uranium_piece_ore').displayName('Uranium Ore Piece')
	e.create('cobble_dough').displayName('Cobble Dough')
	e.create('obsidian_dough').displayName('Obsidian Dough')
	e.create('soulsand_dough').displayName('Soul Sand Dough')
	e.create('dirt_dough').displayName('Dirt Dough')
	e.create('chocolat_dough').displayName('Chocolat Dough')
	e.create('base_cobble_cake').displayName('Cobble Cake Base')
	e.create('base_obsidian_cake').displayName('Obsidian Cake Base')
	e.create('base_soulsand_cake').displayName('Soul Sand Cake Base')
	e.create('base_dirt_cake').displayName('Dirt Cake Base')
	e.create('base_chocolat_cake').displayName('Chocolat Cake Base')
	e.create('baked_cobble_cake').displayName('Cobble Cake Baked')
	e.create('baked_obsidian_cake').displayName('Obsidian Cake Baked')
	e.create('baked_soulsand_cake').displayName('Soul Sand Cake Baked')
	e.create('baked_dirt_cake').displayName('Dirt Cake Baked')
	e.create('baked_chocolat_cake').displayName('Chocolat Cake Baked')
	e.create('inferium_seed').displayName('§eInferium Seed Base')
	e.create('prudentium_seed').displayName('§2Prudentium Seed Base')
	e.create('tertium_seed').displayName('§6Tertium Seed Base')
	e.create('imperium_seed').displayName('§9Imperium Seed Base')
	e.create('supremium_seed').displayName('§cSupremium Seed Base')
	e.create('insanium_seed').displayName('§5Insanium Seed Base')
	e.create('demonium_seed').displayName('§8Demonium Seed Base')
	e.create('mana_device').displayName('Mana Device')
	e.create('natura_device').displayName('Natura Device')
	e.create('gaia_device').displayName('Gaia Device')
	e.create('alfsteel_device').displayName('Alfsteel Device')
	e.create('eternal_singularity').displayName('Eternal Singularity')
	e.create('singu_asgard').displayName('Asgard Singularity')
	e.create('singu_vanaheim').displayName('Vanaheim Singularity')
	e.create('singu_alfheim').displayName('Alfheim Singularity')
	e.create('singu_midgard').displayName('Midgard Singularity')
	e.create('singu_jotunheim').displayName('Jötunheim Singularity')
	e.create('singu_muspelheim').displayName('Muspelheim Singularity')
	e.create('singu_niflheim').displayName('Niflheim Singularity')
	e.create('singu_nidavellir').displayName('Nidavellir Singularity')
	e.create('singu_helheim').displayName('Helheim Singularity')
	e.create('singu_ragnarok').displayName('Ragnarök Singularity')
	e.create('empty_tier_installer').displayName('Empty Tier Installer').maxStackSize(16)
	e.create('basic_tier_card').displayName('§aBasic Tier Card').maxStackSize(16)
	e.create('advanced_tier_card').displayName('§cAdvanced Tier Card').maxStackSize(16)
	e.create('elite_tier_card').displayName('§bElite Tier Card').maxStackSize(16)
	e.create('ultimate_tier_card').displayName('§dUltimate Tier Card').maxStackSize(16)
	e.create('incomplete_calculation_processor').displayName('Incomplete Calculation Processor')
	e.create('incomplete_engineering_processor').displayName('Incomplete Engineering Processor')
	e.create('incomplete_logic_processor').displayName('Incomplete Logic Processor')
	e.create('incomplete_black_processor').displayName('Incomplete Black Processor')
	e.create('black_processor').displayName('Black Processor')
	e.create('black_processor_press').displayName('Black Processor Press')
	e.create('printed_black_processor').displayName('Printed Black Circuit')
	e.create('rune_mold').displayName('Rune Mold')
	e.create('shadow_steel_plate').displayName('Shadow Steel Plate')
	e.create('refined_radiance_plate').displayName('Refined Radiance Plate').glow(true)
	e.create('overcharged_plate').displayName('Overcharged Plate').glow(true)
	e.create('empty_infusion_crystal').displayName('Empty Infusion Crystal').maxStackSize(1)
	e.create('canister_press').displayName('Canister Press')
	e.create('blackstone_stick').displayName('Blackstone Stick')
	e.create('purified_charged_certus_quartz_crystal').displayName('Pure Charged Certus Quartz Crystal')
	e.create('antimatter_silicon').displayName('Tiny Antimatter Rubber').glow(true)
	e.create('incomplete_draconium_core').displayName('Incomplete Draconium Core')
	e.create('crushed_electrum').displayName('Crushed Electrum')
	e.create('crushed_constantan').displayName('Crushed Constantan')
	e.create('crushed_bronze').displayName('Crushed Bronze')
	e.create('crushed_invar').displayName('Crushed Invar')
	e.create('mythicbotany:crushed_elementium').displayName('Crushed Elementium')
	e.create('tinkersarchery:crushed_tantalum').displayName('Crushed Tantalum')
	e.create('insanium_paper').displayName('Insanium Sandpaper')
	e.create('prosperity_dust').displayName('Prosperity Dust')
	e.create('lapis_imbued_obsidian_plate').displayName('Lapis Imbued Obsidian Plate')
	e.create('integrated_circuit').displayName('Integrated Circuit')
	e.create('cobalt_plate').displayName('Cobalt Plate')
	e.create('steel_gear').displayName('Steel Gear')
	e.create('leather_book_cover').displayName('Leather Book Cover')
	e.create('paper_stacks').displayName('Paper Stacks')
	e.create('gear_mold').displayName('Gear Mold')
	e.create('base_addon').displayName('Base Addon')
	e.create('nautilus_meal').displayName('Nautilus Meal')
	e.create('creative_energy_core').displayName('§dCreative Energy Core')
	e.create('rune_mold_alt').displayName('Flawless Rune Mold').glow(true)
	e.create('uci1').displayName('First Compressed Ingot')
	e.create('uci2').displayName('Second Compressed Ingot')
	e.create('uci3').displayName('Third Compressed Ingot')
	e.create('uci4').displayName('Fourth Compressed Ingot')
	e.create('uci5').displayName('Fifth Compressed Ingot')
	e.create('uci6').displayName('Sixth Compressed Ingot')
	e.create('uci7').displayName('Seventh Compressed Ingot')
	e.create('ui1').displayName('§4Ingot α "Alpha"').glow(true)
	e.create('ui2').displayName('§6Ingot β "Beta"').glow(true)
	e.create('ui3').displayName('§eIngot γ "Gamma"').glow(true)
	e.create('ui4').displayName('§aIngot δ "Delta"').glow(true)
	e.create('ui5').displayName('§9Ingot ε "Epsilon"').glow(true)
	e.create('ui6').displayName('§5Ingot ζ "Zêta"').glow(true)
	e.create('ui7').displayName('§dIngot η "Êta"').glow(true)
	e.create('ci1').displayName('Mannaz Ingot ᛗ')
	e.create('ci2').displayName('Raidō Ingot ᚱ')
	e.create('ci3').displayName('Fehu Ingot ᚠ')
	e.create('ci4').displayName('Algiz Ingot ᛉ')
	e.create('ci5').displayName('Ōthalan Ingot ᛟ')
	e.create('wyvern_catalyst').displayName('Wyvern Catalyst')
	e.create('draconic_catalyst').displayName('Draconic Catalyst')
	e.create('chaotic_catalyst').displayName('Chaotic Catalyst')
	e.create('infinite_resonator').displayName('Ultimate Resonator').maxDamage(999999999).unstackable()
	e.create('machinarium_ingot').displayName('Machinarium Ingot')
	e.create('demonium_essence').displayName('Demonium Essence')
	e.create('demonium_gemstone').displayName('Demonium Gemstone')
	e.create('demonium_ingot').displayName('Demonium Ingot')
	e.create('demonium_nugget').displayName('Demonium Nugget')
})
onEvent('item.modification', e => {
	e.modify('xreliquary:witch_hat', item => {
		item.maxStackSize = 64
	})
	e.modify(['miniutilities:golden_lasso', 'telepastries:custom_cake', 'telepastries:overworld_cake', 'telepastries:nether_cake', 'telepastries:end_cake', 'mob_grinding_utils:jumbo_tank', 'mob_grinding_utils:tank', 'tconstruct:seared_fuel_tank', 'tconstruct:seared_ingot_tank', 'tconstruct:scorched_fuel_tank', 'tconstruct:scorched_fuel_gauge', 'tconstruct:scorched_ingot_tank', 'industrialforegoing:supreme_black_hole_tank', 'industrialforegoing:advanced_black_hole_tank', 'industrialforegoing:simple_black_hole_tank', 'industrialforegoing:pity_black_hole_tank', 'industrialforegoing:common_black_hole_tank'], item => {
		item.maxStackSize = 1
	})
})