events.listen('jei.hide.items', function (e) {
  e.hide([
    'telepastries:lost_city_cake',
    'telepastries:twilight_cake',
    'create:copper_ore',
    'mekanism:copper_ore',
    'tconstruct:copper_ore',
    'immersiveengineering:ore_copper',
    'create:copper_nugget',
    'immersiveengineering:nugget_copper',
    'tconstruct:copper_nugget',
    'mekanism:nugget_copper',
    'exnihilosequentia:ingot_copper',
    'create:copper_ingot',
    'immersiveengineering:ingot_copper',
    'mekanism:ingot_copper',
    'tconstruct:copper_ingot',
    'immersiveengineering:plate_copper',
    'create:copper_sheet',
    'mekanism:dust_copper',
    'immersiveengineering:wire_copper',
    'exnihilosequentia:ingot_aluminum',
    'appliedenergistics2:nether_quartz_dust',
    'titanium:iron_gear',
    'titanium:diamond_gear',
    'titanium:gold_gear',
    'create:iron_sheet',
    'immersiveengineering:plate_iron',
    'immersiveengineering:stick_iron',
    'immersiveengineering:plate_gold',
    'create:golden_sheet',
    'immersiveengineering:dust_gold',
    'mekanism:dust_gold',
    'appliedenergistics2:gold_dust',
    'appliedenergistics2:iron_dust',
    'mekanism:dust_iron',
    'immersiveengineering:dust_iron',
    'createaddition:diamond_grit',
    'mekanism:dust_diamond',
    'mekanism:dust_lapis_lazuli',
    'createdeco:zinc_sheet',
    'exnihilosequentia:ingot_zinc',
    'immersiveengineering:ingot_nickel',
    'exnihilosequentia:ingot_nickel',
    'immersiveengineering:plate_nickel',
    'immersiveengineering:nugget_nickel',
    'immersiveengineering:dust_nickel',
    'immersiveengineering:dust_uranium',
    'mekanism:dust_tin',
    'immersiveengineering:dust_silver',
    'immersiveengineering:dust_lead',
    'mekanism:dust_lead',
    'exnihilosequentia:ingot_uranium',
    'immersiveengineering:ingot_uranium',
    'immersiveengineering:ore_nickel',
    'immersiveengineering:nugget_uranium',
    'immersiveengineering:ore_uranium',
    'mekanism:ingot_tin',
    'mekanism:nugget_tin',
    'mekanism:tin_ore',
    'immersiveengineering:nugget_silver',
    'exnihilosequentia:ingot_silver',
    'immersiveengineering:ingot_silver',
    'immersiveengineering:ore_silver',
    'immersiveengineering:plate_silver',
    'immersiveengineering:ore_lead',
    'mekanism:lead_ore',
    'mekanism:nugget_lead',
    'immersiveengineering:nugget_lead',
    'exnihilosequentia:ingot_lead',
    'immersiveengineering:ingot_lead',
    'mekanism:ingot_lead',
    'immersiveengineering:plate_lead',
    'immersiveengineering:slag',
    'immersivepetroleum:bitumen',
    'immersiveengineering:dust_sulfur',
    'mekanism:dust_sulfur',
    'immersiveengineering:dust_wood',
    'mekanism:sawdust',
    'excompressum:wood_chippings',
    'mekanism:dust_obsidian',
    'mekanism:dust_emerald',
    'immersiveengineering:nugget_steel',
    'immersiveengineering:ingot_steel',
    'immersiveengineering:dust_steel',
    'mekanism:nugget_bronze',
    'mekanism:ingot_bronze',
    'mekanism:dust_bronze',
    'immersiveengineering:nugget_constantan',
    'immersiveengineering:ingot_constantan',
    'immersiveengineering:dust_constantan',
    'immersiveengineering:plate_constantan',
    'immersiveengineering:nugget_electrum',
    'immersiveengineering:dust_electrum',
    'immersiveengineering:plate_electrum',
    'immersiveengineering:ingot_electrum',
    'createdeco:netherite_nugget',
    'exnihilosequentia:end_cake',
    'mining_dimension:teleporter',
    'appliedenergistics2:charger',
    /appliedenergistics2:facade/,
    'mysticalagriculture:rubber_seeds',
    'mysticalagriculture:graphite_seeds',
    'mysticalagriculture:chrome_seeds',
    'mysticalagriculture:titanium_seeds',
    'mysticalagriculture:tungsten_seeds',
    'mysticalagriculture:mithril_seeds',
    'mysticalagriculture:platinum_seeds',
    'mysticalagriculture:iridium_seeds',
    /mysticalagriculture:soul_jar/,
    'exnihilosequentia:ingot_tin',
    'immersiveengineering:dust_copper',
    'botania:pestle_and_mortar',
    'industrialforegoing:black_hole_controller',
    'usrg:claygenerator',
    'usrg:dirtgenerator',
    'usrg:endgenerator',
    'usrg:fungusgenerator',
    'usrg:glowstonegenerator',
    'usrg:grassgenerator',
    'usrg:gravelgenerator',
    'usrg:icegenerator',
    'usrg:nethergenerator',
    'usrg:redstonegenerator',
    'usrg:nethercrushedgenerator',
    'usrg:sandgenerator',
    'usrg:snowgenerator',
    'usrg:soulgenerator',
    'usrg:oregenerator',
    'usrg:dyegenerator',
    'usrg:dustgenerator',
    'usrg:endcrushedgenerator',
    'usrg:quartzgenerator',
    'usrg:obsidiangenerator',
    'extendedcrafting:ultimate_singularity',
    'ironfurnaces:upgrade_copper',
    'ironfurnaces:upgrade_iron',
    'ironfurnaces:upgrade_silver',
    'ironfurnaces:upgrade_gold',
    'ironfurnaces:upgrade_gold',
    'ironfurnaces:upgrade_obsidian2',
    'bhc:wither_bone',
    'ironchest:wood_to_iron_chest_upgrade',
    'ironchest:copper_to_silver_chest_upgrade',
    'ironchest:iron_to_gold_chest_upgrade',
    'metalbarrels:wood_to_iron',
    'metalbarrels:wood_to_silver',
    'metalbarrels:wood_to_gold',
    'metalbarrels:wood_to_diamond',
    'metalbarrels:wood_to_obsidian',
    'metalbarrels:wood_to_netherite',
    'metalbarrels:copper_to_silver',
    'metalbarrels:copper_to_gold',
    'metalbarrels:copper_to_diamond',
    'metalbarrels:copper_to_obsidian',
    'metalbarrels:iron_to_gold',
    'metalbarrels:iron_to_diamond',
    'metalbarrels:iron_to_obsidian',
    'metalbarrels:silver_to_diamond',
    'metalbarrels:silver_to_obsidian',
    'metalbarrels:gold_to_obsidian',
    'metalbarrels:wood_to_crystal',
    'metalbarrels:copper_to_crystal',
    'metalbarrels:iron_to_crystal',
    'metalbarrels:silver_to_crystal',
    'metalbarrels:gold_to_crystal',
    'exnihilosequentia:spruce_crucible',
    'exnihilosequentia:birch_crucible',
    'exnihilosequentia:acacia_crucible',
    'exnihilosequentia:crimson_crucible',
    'exnihilosequentia:warped_crucible',
    'exnihilosequentia:jungle_crucible',
    'exnihilosequentia:dark_oak_crucible',
    'exnihilosequentia:crucible_wood',
    'immersiveengineering:coal_coke',
    'appliedenergistics2:inscriber',
    'ae2wtlib:wireless_universal_terminal',
    /ftblibrary:fluid_container/,
    /tconstruct:crafting_station/,
    /tconstruct:tinker_station/,
    /tconstruct:part_builder/,
    'trofers:large_plate',
    'trofers:medium_plate',
    'trofers:small_plate',
    'trofers:large_pillar',
    'trofers:medium_pillar',
    'trofers:small_pillar',
    'mekanism:ultimate_smelting_factory',
    'mekanism:ultimate_enriching_factory',
    'mekanism:ultimate_crushing_factory',
    'mekanism:ultimate_compressing_factory',
    'mekanism:ultimate_combining_factory',
    'mekanism:ultimate_purifying_factory',
    'mekanism:ultimate_injecting_factory',
    'mekanism:ultimate_infusing_factory',
    'mekanism:ultimate_sawing_factory',
    'mekanism:basic_smelting_factory',
    'mekanism:basic_enriching_factory',
    'mekanism:basic_crushing_factory',
    'mekanism:basic_compressing_factory',
    'mekanism:basic_combining_factory',
    'mekanism:basic_purifying_factory',
    'mekanism:basic_injecting_factory',
    'mekanism:basic_infusing_factory',
    'mekanism:basic_sawing_factory',
    'mekanism:advanced_smelting_factory',
    'mekanism:advanced_enriching_factory',
    'mekanism:advanced_crushing_factory',
    'mekanism:advanced_compressing_factory',
    'mekanism:advanced_combining_factory',
    'mekanism:advanced_purifying_factory',
    'mekanism:advanced_injecting_factory',
    'mekanism:advanced_infusing_factory',
    'mekanism:advanced_sawing_factory',
    'mekanism:elite_smelting_factory',
    'mekanism:elite_enriching_factory',
    'mekanism:elite_crushing_factory',
    'mekanism:elite_compressing_factory',
    'mekanism:elite_combining_factory',
    'mekanism:elite_purifying_factory',
    'mekanism:elite_injecting_factory',
    'mekanism:elite_infusing_factory',
    'mekanism:elite_sawing_factory',
    'ae2wtlib:wireless_fluid_terminal',
    'appliedenergistics2:name_press',
    'immersiveengineering:mold_plate',
    'immersiveengineering:mold_gear',
    'immersiveengineering:mold_wire',
    'immersiveengineering:mold_rod',
    'immersiveengineering:mold_unpacking',
    'immersiveengineering:mold_packing_9',
    'immersiveengineering:mold_packing_4',
    Item.of('patchouli:guide_book', '{"patchouli:book":"simplyjetpacks:guidebook"}'),
    'immersiveengineering:furnace_heater',
    'kubejs:livingrock_wrath_slab',
    'kubejs:livingrock_air_slab',
    'kubejs:livingrock_alfheim_slab',
    'kubejs:livingrock_asgard_slab',
    'kubejs:livingrock_autumn_slab',
    'kubejs:livingrock_earth_slab',
    'kubejs:livingrock_envy_slab',
    'kubejs:livingrock_fire_slab',
    'kubejs:livingrock_gluttony_slab',
    'kubejs:livingrock_niflheim_slab',
    'kubejs:livingrock_nidavellir_slab',
    'kubejs:livingrock_muspelheim_slab',
    'kubejs:livingrock_midgard_slab',
    'kubejs:livingrock_mana_slab',
    'kubejs:livingrock_lust_slab',
    'kubejs:livingrock_jotunheim_slab',
    'kubejs:livingrock_helheim_slab',
    'kubejs:livingrock_greed_slab',
    'kubejs:livingrock_pride_slab',
    'kubejs:livingrock_sloth_slab',
    'kubejs:livingrock_spring_slab',
    'kubejs:livingrock_summer_slab',
    'kubejs:livingrock_vanaheim_slab',
    'kubejs:livingrock_water_slab',
    'kubejs:livingrock_winter_slab',
    'kubejs:incomplete_calculation_processor',
    'kubejs:incomplete_engineering_processor',
    'kubejs:incomplete_logic_processor',
    'kubejs:incomplete_black_processor',
    'kubejs:dummy_fluid_item',
    'mysticalagriculture:infusion_crystal',
    'compactcrafting:match_proxy',
    'compactcrafting:rescan_proxy',
    'storagedrawers:spruce_full_drawers_2',
    'storagedrawers:spruce_full_drawers_1',
    'storagedrawers:oak_trim',
    'storagedrawers:oak_half_drawers_4',
    'storagedrawers:oak_half_drawers_2',
    'storagedrawers:oak_half_drawers_1',
    'storagedrawers:oak_full_drawers_4',
    'storagedrawers:oak_full_drawers_2',
    'storagedrawers:oak_full_drawers_1',
    'storagedrawers:birch_trim',
    'storagedrawers:birch_half_drawers_4',
    'storagedrawers:birch_half_drawers_2',
    'storagedrawers:birch_half_drawers_1',
    'storagedrawers:birch_full_drawers_4',
    'storagedrawers:birch_full_drawers_2',
    'storagedrawers:birch_full_drawers_1',
    'storagedrawers:spruce_trim',
    'storagedrawers:spruce_half_drawers_4',
    'storagedrawers:spruce_half_drawers_2',
    'storagedrawers:spruce_half_drawers_1',
    'storagedrawers:spruce_full_drawers_4',
    'storagedrawers:acacia_full_drawers_2',
    'storagedrawers:acacia_full_drawers_1',
    'storagedrawers:jungle_trim',
    'storagedrawers:jungle_half_drawers_4',
    'storagedrawers:jungle_half_drawers_2',
    'storagedrawers:jungle_half_drawers_1',
    'storagedrawers:jungle_full_drawers_4',
    'storagedrawers:jungle_full_drawers_2',
    'storagedrawers:jungle_full_drawers_1',
    'storagedrawers:dark_oak_trim',
    'storagedrawers:dark_oak_half_drawers_4',
    'storagedrawers:dark_oak_half_drawers_2',
    'storagedrawers:dark_oak_half_drawers_1',
    'storagedrawers:dark_oak_full_drawers_4',
    'storagedrawers:dark_oak_full_drawers_2',
    'storagedrawers:dark_oak_full_drawers_1',
    'storagedrawers:acacia_trim',
    'storagedrawers:acacia_half_drawers_4',
    'storagedrawers:acacia_half_drawers_2',
    'storagedrawers:acacia_half_drawers_1',
    'storagedrawers:acacia_full_drawers_4',
    'storagedrawers:warped_full_drawers_2',
    'storagedrawers:warped_full_drawers_1',
    'storagedrawers:crimson_trim',
    'storagedrawers:crimson_half_drawers_4',
    'storagedrawers:crimson_half_drawers_2',
    'storagedrawers:crimson_half_drawers_1',
    'storagedrawers:crimson_full_drawers_4',
    'storagedrawers:crimson_full_drawers_2',
    'storagedrawers:crimson_full_drawers_1',
    'storagedrawers:warped_trim',
    'storagedrawers:warped_half_drawers_4',
    'storagedrawers:warped_half_drawers_2',
    'storagedrawers:warped_half_drawers_1',
    'storagedrawers:warped_full_drawers_4',
    'exnihilosequentia:chunk_lead',
    'exnihilosequentia:chunk_uranium',
    'exnihilosequentia:chunk_zinc',
    'exnihilosequentia:chunk_nickel',
    'exnihilosequentia:chunk_aluminum',
    'exnihilosequentia:chunk_silver',
    'exnihilosequentia:chunk_gold',
    'exnihilosequentia:chunk_copper',
    'exnihilosequentia:chunk_iron',
    'exnihilosequentia:piece_iron',
    'exnihilosequentia:piece_copper',
    'exnihilosequentia:piece_gold',
    'exnihilosequentia:piece_silver',
    'exnihilosequentia:piece_aluminum',
    'exnihilosequentia:piece_nickel',
    'exnihilosequentia:piece_zinc',
    'exnihilosequentia:piece_lead',
    'exnihilosequentia:piece_uranium',
    'thermal:netherite_plate',
    'tconstruct:plate_red_sand_cast',
    'tconstruct:plate_sand_cast',
    'tconstruct:plate_cast',
    'kubejs:incomplete_draconium_core',
    'mysticalagriculture:passive_soulium_dagger',
    'mysticalagriculture:hostile_soulium_dagger',
    'metalbarrels:wood_to_copper',
    'metalbarrels:copper_to_iron',
    'metalbarrels:iron_to_silver',
    'metalbarrels:silver_to_gold',
    'metalbarrels:gold_to_diamond',
    'metalbarrels:diamond_to_obsidian',
    'metalbarrels:diamond_to_crystal',
    'ironchest:gold_to_diamond_chest_upgrade',
    'ironchest:silver_to_gold_chest_upgrade',
    'ironchest:copper_to_iron_chest_upgrade',
    'ironchest:diamond_to_crystal_chest_upgrade',
    'ironchest:wood_to_copper_chest_upgrade',
    'ironchest:diamond_to_obsidian_chest_upgrade',
    'createdeco:netherite_nugget',
    'projectred-core:copper_ingot',
    'projectred-core:tin_ingot',
    'projectred-core:silver_ingot',
    /cb_microblock:microblock/,
    /simplyjetpacks/,
    'projectred-core:draw_plate',
    'projectred-core:null_routing_chip',
    'cb_microblock:diamond_saw',
    'cb_microblock:iron_saw',
    'cb_microblock:stone_saw',
    'cb_microblock:stone_rod',
    'projectred-core:silicon_chip',
    'projectred-core:pointer',
    'projectred-core:anode',
    'projectred-core:wired_plate',
    'projectred-core:bundled_plate',
    'projectred-core:platformed_plate',
    'projectred-core:energized_silicon_chip',
    'projectred-core:sand_coal_comp',
    'projectred-core:ruby',
    'projectred-core:sapphire',
    'projectred-core:peridot',
    'projectred-core:woven_cloth',
    'projectred-core:sail',
    'mysticalagradditions:end_prosperity_ore',
    'mysticalagriculture:prosperity_ore',
    'mysticalagradditions:nether_prosperity_ore',
    'ironfurnaces:upgrade_silver2',
    'ironfurnaces:upgrade_gold2',
    'ironfurnaces:upgrade_iron2',
    'ironfurnaces:upgrade_netherite',
    'ironfurnaces:upgrade_crystal',
    'ironfurnaces:upgrade_obsidian',
    'ironfurnaces:upgrade_emerald',
    'ironfurnaces:upgrade_diamond',
    'projectred-core:screwdriver',
    'projectred-core:copper_coil',
    'projectred-core:iron_coil',
    'projectred-core:gold_coil',
    'projectred-core:motor',
    'appliedenergistics2:grindstone',
    'appliedenergistics2:flour',
    'tconstruct:wire_red_sand_cast',
    'tconstruct:wire_sand_cast',
    'tconstruct:wire_cast',
    'darkutils:dark_glass',
    'tconstruct:gear_red_sand_cast',
    'tconstruct:gear_sand_cast',
    'tconstruct:gear_cast',
    'creategearaddon:half_shaft_palm_cogwheel',
    'creategearaddon:half_shaft_mahogany_cogwheel',
    'creategearaddon:half_shaft_magic_cogwheel',
    'creategearaddon:cherry_cogwheel',
    'creategearaddon:dead_cogwheel',
    'creategearaddon:fir_cogwheel',
    'creategearaddon:hellbark_cogwheel',
    'creategearaddon:jacaranda_cogwheel',
    'creategearaddon:magic_cogwheel',
    'creategearaddon:mahogany_cogwheel',
    'creategearaddon:palm_cogwheel',
    'creategearaddon:redwood_cogwheel',
    'creategearaddon:large_mahogany_cogwheel',
    'creategearaddon:large_magic_cogwheel',
    'creategearaddon:large_jacaranda_cogwheel',
    'creategearaddon:large_hellbark_cogwheel',
    'creategearaddon:large_fir_cogwheel',
    'creategearaddon:large_dead_cogwheel',
    'creategearaddon:large_cherry_cogwheel',
    'creategearaddon:willow_cogwheel',
    'creategearaddon:umbran_cogwheel',
    'creategearaddon:half_shaft_jacaranda_cogwheel',
    'creategearaddon:half_shaft_hellbark_cogwheel',
    'creategearaddon:half_shaft_fir_cogwheel',
    'creategearaddon:half_shaft_dead_cogwheel',
    'creategearaddon:half_shaft_cherry_cogwheel',
    'creategearaddon:large_willow_cogwheel',
    'creategearaddon:large_umbran_cogwheel',
    'creategearaddon:large_redwood_cogwheel',
    'creategearaddon:large_palm_cogwheel',
    'creategearaddon:large_shaftless_mahogany_cogwheel',
    'creategearaddon:large_shaftless_fir_cogwheel',
    'creategearaddon:shaftless_umbran_cogwheel',
    'creategearaddon:shaftless_magic_cogwheel',
    'creategearaddon:shaftless_dead_cogwheel',
    'creategearaddon:large_half_shaft_redwood_cogwheel',
    'creategearaddon:large_half_shaft_palm_cogwheel',
    'creategearaddon:large_half_shaft_mahogany_cogwheel',
    'creategearaddon:large_shaftless_hellbark_cogwheel',
    'creategearaddon:shaftless_willow_cogwheel',
    'creategearaddon:shaftless_mahogany_cogwheel',
    'creategearaddon:shaftless_fir_cogwheel',
    'creategearaddon:large_half_shaft_umbran_cogwheel',
    'creategearaddon:half_shaft_willow_cogwheel',
    'creategearaddon:half_shaft_umbran_cogwheel',
    'creategearaddon:half_shaft_redwood_cogwheel',
    'creategearaddon:large_shaftless_jacaranda_cogwheel',
    'creategearaddon:large_shaftless_cherry_cogwheel',
    'creategearaddon:shaftless_palm_cogwheel',
    'creategearaddon:shaftless_hellbark_cogwheel',
    'creategearaddon:large_half_shaft_willow_cogwheel',
    'creategearaddon:large_half_shaft_fir_cogwheel',
    'creategearaddon:large_half_shaft_dead_cogwheel',
    'creategearaddon:large_half_shaft_cherry_cogwheel',
    'creategearaddon:large_shaftless_magic_cogwheel',
    'creategearaddon:large_shaftless_dead_cogwheel',
    'creategearaddon:shaftless_redwood_cogwheel',
    'creategearaddon:shaftless_jacaranda_cogwheel',
    'creategearaddon:shaftless_cherry_cogwheel',
    'creategearaddon:large_half_shaft_magic_cogwheel',
    'creategearaddon:large_half_shaft_jacaranda_cogwheel',
    'creategearaddon:large_half_shaft_hellbark_cogwheel',
    'creategearaddon:large_shaftless_willow_cogwheel',
    'creategearaddon:large_shaftless_umbran_cogwheel',
    'creategearaddon:large_shaftless_redwood_cogwheel',
    'creategearaddon:large_shaftless_palm_cogwheel',
    'miniutilities:laser_port',
    'miniutilities:solar_panel_controller',
    'miniutilities:solar_panel',
    'miniutilities:speed_upgrade',
    'miniutilities:magical_egg',
    'miniutilities:quantum_quarry',
    'miniutilities:lunar_panel',
    'miniutilities:ender_tile',
    'miniutilities:chorus_tile',
    'miniutilities:peacock_angel_ring',
    'miniutilities:bat_angel_ring',
    'miniutilities:feather_angel_ring',
    'miniutilities:ender_dragon_angel_ring',
    'miniutilities:gold_angel_ring',
    'miniutilities:laser_hub',
    'miniutilities:ender_pearl_block',
    'miniutilities:blursed_earth',
    'miniutilities:blessed_earth',
    'miniutilities:cursed_earth',
    'miniutilities:mechanical_placer',
    'miniutilities:mechanical_miner',
    'miniutilities:ender_dust',
    'mob_grinding_utils:spikes',
    'miniutilities:dark_glass',
    'immersiveengineering:alloybrick',
    'immersiveengineering:slab_alloybrick',
    'exnihilosequentia:infesting_leaves',
    'exnihilosequentia:infested_leaves',
    'pamhc2foodcore:fruitpunchitem',
    'quark:matrix_enchanter',
    'mysticalagriculture:chrome_essence',
    'mysticalagriculture:rubber_essence',
    'mysticalagriculture:platinum_essence',
    'mysticalagriculture:graphite_essence',
    'architects_palette:withered_bone',
    'compactmachines:solid_wall',
    'thermal:creosote_bucket',
    'thermal:device_hive_extractor',
    'pamhc2foodcore:doughitem',
    'mekanism:dust_netherite',
    'mekanism:dust_quartz',
    'industrialforegoing:item_transporter_type',
    'industrialforegoing:fluid_transporter_type',
    'industrialforegoing:world_transporter_type',
    'betterendforge:ender_dust',
    'thermal:ender_pearl_dust',
    'thermal:ender_grenade',
    'thermal:ender_tnt',
    'simplyjetpacks:flux_chestplate',
    'simplyjetpacks:armorplating_te5_enderium',
    'envirocore:radiant_modifier',
    'envirocore:thermal_modifier',
    'envirocore:piezo_modifier',
    'envirocore:electrostatic_modifier',
    'envirocore:creative_energy_source',
    'mysticalagriculture:tungsten_essence',
    'appliedenergistics2:quartz_growth_accelerator',
    'masterfulmachinery:explosivo_energy_port_energy_output',
    'masterfulmachinery:explosivo_fluid_port_fluids_output',
    'masterfulmachinery:explosivo_gas_port_mekanism_gas_output',
    'masterfulmachinery:explosivo_kinetic_port_create_rotation_output',
    'masterfulmachinery:barrel_fluid_port_fluids_output',
    'masterfulmachinery:bloodbath_fluid_port_fluids_output',
    'masterfulmachinery:projector',
    'masterfulmachinery:structure_generator',
    'masterfulmachinery:structure_gen_device',
    'mysticalagriculture:iridium_essence',
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"thermal:creosote",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"cofh_core:honey",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_starmetal",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_arcane_gold",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_cloggrum",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_ebony_psimetal",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_flux_infused",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_forgotten_metal",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_froststeel",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_iesnium",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_ivory_psimetal",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_neptunium",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_psimetal",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_quicksilver",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_regalium",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"materialis:molten_utherium",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"tconstruct:molten_tungsten",Amount:2147483647}}]}}'),
    Item.of('mekanism:creative_fluid_tank', '{mekData:{FluidTanks:[{Tank:0b,stored:{FluidName:"tconstruct:molten_pewter",Amount:2147483647}}]}}')
  ])
})
onEvent('jei.hide.fluids', e => {
  e.hide('thermal:creosote')
  e.hide('cofh_core:honey')
})
onEvent('jei.add.items', e => {
  e.add([
    Item.of('appliedenergistics2:facade', '{item:"minecraft:stone"}'),
    'thermal:sapphire_ore',
    'thermal:sapphire_block',
    'thermal:sapphire',
    'thermal:ruby_ore',
    'thermal:ruby_block',
    'thermal:ruby',
    'tconstruct:crafting_station',
    Item.of('tconstruct:tinker_station', '{texture:"minecraft:oak_planks"}'),
    Item.of('tconstruct:part_builder', '{texture:"minecraft:oak_planks"}'),
    'simplyjetpacks:particle_smoke',
    'simplyjetpacks:particle_rainbow',
    'simplyjetpacks:leather_strap',
    'simplyjetpacks:pilot_goggles_gold',
    'simplyjetpacks:particle_none',
    'simplyjetpacks:jetpack_te3',
    'simplyjetpacks:jetpack_te3_armored',
    'simplyjetpacks:jetpack_te4',
    'simplyjetpacks:jetpack_te4_armored',
    'simplyjetpacks:jetpack_te5',
    'simplyjetpacks:pilot_goggles_iron',
    'simplyjetpacks:jetpack_te5_enderium',
    'simplyjetpacks:armorplating_te5',
    'simplyjetpacks:jetpack_potato',
    'simplyjetpacks:armorplating_te1',
    'simplyjetpacks:armorplating_te2',
    'simplyjetpacks:armorplating_te3',
    'simplyjetpacks:armorplating_te4',
    'simplyjetpacks:particle_blend',
    'simplyjetpacks:particle_flame',
    'simplyjetpacks:particle_soul',
    'simplyjetpacks:particle_snow',
    'simplyjetpacks:thruster_te1',
    'simplyjetpacks:thruster_te2',
    'simplyjetpacks:thruster_te3',
    'simplyjetpacks:thruster_te4',
    'simplyjetpacks:thruster_te5',
    'simplyjetpacks:jetpack_te1',
    'simplyjetpacks:jetpack_te1_armored',
    'simplyjetpacks:jetpack_te2',
    'simplyjetpacks:jetpack_te2_armored'
  ])
})
onEvent('item.tooltip', tooltip => {
  tooltip.add('botania:mana_bottle', ["§l§4DON'T DRINK IT!"])

  tooltip.addAdvanced([
    //Pick
    'minecraft:wooden_pickaxe', 'minecraft:stone_pickaxe', 'betterendforge:thallasium_pickaxe', 'betterendforge:terminite_pickaxe', 'botania:manasteel_pick', 'minecraft:netherite_pickaxe', 'minecraft:diamond_pickaxe', 'minecraft:iron_pickaxe', 'minecraft:golden_pickaxe', 'create_stuff_additions:blazing_pickaxe', 'byg:pendorite_pickaxe', 'appliedenergistics2:nether_quartz_pickaxe', 'appliedenergistics2:certus_quartz_pickaxe', 'betterendforge:aeternium_pickaxe', 'botania:glass_pickaxe', 'create_stuff_additions:copper_pickaxe', 'create_stuff_additions:zinc_pickaxe', 'botania:elementium_pickaxe', 'create_stuff_additions:brass_pickaxe', 'immersiveengineering:pickaxe_steel',
    //Axe
    'minecraft:wooden_axe', 'minecraft:stone_axe', 'minecraft:golden_axe', 'minecraft:iron_axe', 'minecraft:diamond_axe', 'minecraft:netherite_axe', 'appliedenergistics2:certus_quartz_axe', 'appliedenergistics2:nether_quartz_axe', 'betterendforge:aeternium_axe', 'betterendforge:thallasium_axe', 'betterendforge:terminite_axe', 'botania:manasteel_axe', 'botania:elementium_axe', 'create_stuff_additions:brass_axe', 'create_stuff_additions:zinc_axe', 'create_stuff_additions:copper_axe', 'create_stuff_additions:blazing_axe', 'byg:pendorite_axe', 'immersiveengineering:axe_steel',
    //Shovel
    'minecraft:wooden_shovel', 'minecraft:stone_shovel', 'minecraft:golden_shovel', 'minecraft:iron_shovel', 'minecraft:diamond_shovel', 'minecraft:netherite_shovel', 'appliedenergistics2:certus_quartz_shovel', 'appliedenergistics2:nether_quartz_shovel', 'betterendforge:aeternium_shovel', 'immersiveengineering:shovel_steel', 'betterendforge:thallasium_shovel', 'betterendforge:terminite_shovel', 'botania:manasteel_shovel', 'botania:elementium_shovel', 'create_stuff_additions:brass_shovel', 'create_stuff_additions:zinc_shovel', 'create_stuff_additions:copper_shovel', 'create_stuff_additions:blazing_shovel', 'byg:pendorite_shovel',
    //Hoe
    'minecraft:wooden_hoe', 'minecraft:stone_hoe', 'minecraft:golden_hoe', 'minecraft:iron_hoe', 'minecraft:diamond_hoe', 'minecraft:netherite_hoe', 'appliedenergistics2:certus_quartz_hoe', 'appliedenergistics2:nether_quartz_hoe', 'betterendforge:aeternium_hoe', 'betterendforge:thallasium_hoe', 'betterendforge:terminite_hoe', 'botania:manasteel_hoe', 'botania:elementium_hoe', 'create_stuff_additions:brass_hoe', 'create_stuff_additions:zinc_hoe', 'create_stuff_additions:copper_hoe', 'immersiveengineering:hoe_steel', 'byg:pendorite_hoe'
  ], (item, advanced, text) => {
    text.add(1, Text.of('§4This tool has zero durability'))
    text.add(2, Text.of('§3Use tinker tools instead'))
  })

  tooltip.addAdvanced([
    'minecraft:wooden_sword', 'minecraft:stone_sword', 'minecraft:golden_sword', 'minecraft:iron_sword', 'minecraft:diamond_sword', 'minecraft:netherite_sword', 'appliedenergistics2:certus_quartz_sword', 'appliedenergistics2:nether_quartz_sword', 'betterendforge:aeternium_sword', 'betterendforge:thallasium_sword', 'betterendforge:terminite_sword', 'botania:manasteel_sword', 'botania:elementium_sword', 'create_stuff_additions:brass_sword', 'create_stuff_additions:zinc_sword', 'create_stuff_additions:copper_sword', 'immersiveengineering:sword_steel', 'byg:pendorite_sword'
  ], (item, advanced, text) => {
    text.add(1, Text.of('§4This weapon has zero durability'))
    text.add(2, Text.of('§3Use tinker weapons instead'))
  })

  //Resonator  
  tooltip.addAdvanced(['kubejs:infinite_resonator'], (item, advanced, text) => { text.add(1, Text.of('§7I have a lot of durability.')) })


  //Jelly Baby
  tooltip.addAdvanced(['kubejs:nether_jelly_baby'], (item, advanced, text) => { text.add(1, Text.of('§6Gives Fire Resistance for 5 minutes')) })
  tooltip.addAdvanced(['kubejs:mining_jelly_baby'], (item, advanced, text) => { text.add(1, Text.of('§6Gives Haste II for 5 minutes')) })
  tooltip.addAdvanced(['kubejs:overworld_jelly_baby'], (item, advanced, text) => { text.add(1, Text.of('§6Gives Resistance II for 5 minutes')) })
  tooltip.addAdvanced(['kubejs:end_jelly_baby'], (item, advanced, text) => { text.add(1, Text.of('§6Gives Slow Falling for 1 minutes')) })

  //Cobble For Days
  tooltip.addAdvanced(['cobblefordays:tier_1'], (item, advanced, text) => { text.add(1, Text.of('§7Generate 1 cobble every 40 ticks')) })
  tooltip.addAdvanced(['cobblefordays:tier_2'], (item, advanced, text) => { text.add(1, Text.of('§7Generate 1 cobble every 20 ticks')) })
  tooltip.addAdvanced(['cobblefordays:tier_3'], (item, advanced, text) => { text.add(1, Text.of('§7Generate 1 cobble every 10 ticks')) })
  tooltip.addAdvanced(['cobblefordays:tier_4'], (item, advanced, text) => { text.add(1, Text.of('§7Generate 1 cobble every 5 ticks')) })
  tooltip.addAdvanced(['cobblefordays:tier_5'], (item, advanced, text) => { text.add(1, Text.of('§7Generate 1 cobble every 1 ticks')) })

  //Tinker
  tooltip.addAdvanced(['tconstruct:tool_handle_cast', 'tconstruct:tool_binding_cast', 'tconstruct:rod_cast', 'tinkersarchery:arrow_shaft_cast', 'tinkersarchery:bowguide_cast'], (item, advanced, text) => { text.add(1, Text.of('§7Material Cost: 1')) })
  tooltip.addAdvanced(['materialis:wrench_head_cast', 'tconstruct:small_blade_cast', 'tconstruct:small_axe_head_cast', 'tconstruct:pickaxe_head_cast', 'tconstruct:repair_kit_cast', 'tdelight:naginata_head_cast', 'tdelight:mace_head_cast', 'tinkersarchery:bowshaft_cast', 'tinkersarchery:arrowhead_cast', 'tinkersarchery:crossbow_arm_cast'], (item, advanced, text) => { text.add(1, Text.of('§7Material Cost: 2')) })
  tooltip.addAdvanced(['tconstruct:tough_handle_cast'], (item, advanced, text) => { text.add(1, Text.of('§7Material Cost: 3')) })
  tooltip.addAdvanced(['tconstruct:large_plate_cast', 'tinkersarchery:large_bowshaft_cast'], (item, advanced, text) => { text.add(1, Text.of('§7Material Cost: 4')) })
  tooltip.addAdvanced(['tconstruct:broad_axe_head_cast', 'tconstruct:broad_blade_cast', 'tconstruct:hammer_head_cast'], (item, advanced, text) => { text.add(1, Text.of('§7Material Cost: 8')) })

  //Envirocore Modifier
  tooltip.addAdvanced(['envirocore:radiant_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Allows lightning rod to gen passively in sunny weather')) })
  tooltip.addAdvanced(['envirocore:piezo_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Allows solars to gen in rain/thunderstorms from vibrations')) })
  tooltip.addAdvanced(['envirocore:electrostatic_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Allows Lightning rods to gen passively in rain and thunder')) })
  tooltip.addAdvanced(['envirocore:frequency_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Speeds up miners')) })
  tooltip.addAdvanced(['envirocore:bandwidth_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Increases amount of mined items')) })
  tooltip.addAdvanced(['envirocore:amplification_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Is new Accuracy Modifier for lenses')) })
  tooltip.addAdvanced(['envirocore:interdimensional_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Give all drops from all dimensions')) })
  tooltip.addAdvanced(['envirocore:dimensional_modifier'], (item, advanced, text) => { text.add(1, Text.of('§9Give you drops from the same dimension but bypass the biome requirements')) })
})
events.listen('jei.information', function (e) {
  e.add('bhc:red_heart', ['Drop from passive mobs'])
  e.add('bhc:yellow_heart', ['Drop from bosses'])
  e.add('bhc:green_heart', ['Drop from Ender Dragon'])
  e.add('bhc:blue_heart', ['Drop from Piglin Brute'])
  e.add('telepastries:custom_cake', ['You can refill this cake with Mining Jelly Baby'])
  e.add('telepastries:end_cake', ['You can refill this cake with End Jelly Baby'])
  e.add('telepastries:overworld_cake', ['You can refill this cake with Overworld Jelly Baby'])
  e.add('telepastries:nether_cake', ['You can refill this cake with Nether Jelly Baby'])
  e.add('kubejs:dragonscales_block', ['You can obtain this block by performing the Mark of the Falling Tower Ritual with a Dragon Scale.'])
})