#A list of modid:entity_name entries that will be blocked from spawning.
entityBlockList = ["minecraft:wandering_trader", "rats:plague_doctor", "goblintraders:goblin_trader", "goblintraders:vein_goblin_trader", "ragnagoblin:ragna_goblin"]
#Entity spawn prevention radius (in chunks)
#Range: 4 ~ 12
radius = 8
#Disable all spawns of entities in entityBlockList?
disableSpawns = false

